import type { Deal, Lender } from "./types";

export const initialDeals: Deal[] = [
  {
    id: "deal-1",
    businessName: "Joe's Restaurant",
    fundingAmount: 80000,
    owner: "Maria Santos",
    stage: "offers-received",
    daysInStage: 14,
    priority: "high",
    lastActivity: "Offer received from Credibly",
    industry: "Restaurant",
    annualRevenue: 620000,
    contactName: "Joe Martinez",
    contactEmail: "joe@joesrestaurant.com",
    contactPhone: "(305) 555-0142",
    source: "Meta — Spanish Retargeting",
    internalNotes: "Strong cash flow. Owner responsive. Priority close this week.",
    applications: [
      { id: "app-1", lender: "CAN Capital", submissionDate: "2026-05-28", status: "submitted", assignedUser: "Maria Santos" },
      { id: "app-2", lender: "Credibly", submissionDate: "2026-05-30", status: "approved", notes: "Pre-approved pending docs", assignedUser: "Maria Santos" },
      { id: "app-3", lender: "Rapid Finance", submissionDate: "2026-06-02", status: "under-review", assignedUser: "Alex Rivera" },
      { id: "app-4", lender: "OnDeck", submissionDate: "2026-06-04", status: "submitted", assignedUser: "Maria Santos" },
    ],
    offers: [
      { id: "off-1", lender: "Credibly", amount: 75000, factorRate: 1.28, term: "12 months", paymentFrequency: "Daily", status: "received", expirationDate: "2026-06-20", dailyPayment: 312 },
      { id: "off-2", lender: "CAN Capital", amount: 80000, factorRate: 1.32, term: "14 months", paymentFrequency: "Weekly", status: "presented", expirationDate: "2026-06-18", dailyPayment: 298 },
    ],
    documents: [
      { id: "doc-1", name: "Bank Statements (3 mo)", type: "Bank Statements", status: "verified", uploadedAt: "2026-05-25" },
      { id: "doc-2", name: "Driver License", type: "ID", status: "verified", uploadedAt: "2026-05-25" },
      { id: "doc-3", name: "Voided Check", type: "Banking", status: "received", uploadedAt: "2026-05-26" },
      { id: "doc-4", name: "Funding Agreement", type: "Agreement", status: "missing", uploadedAt: null },
    ],
    tasks: [
      { id: "task-1", title: "Present offers to client", owner: "Maria Santos", dueDate: "2026-06-12", status: "in-progress", priority: "high" },
      { id: "task-2", title: "Collect signed funding agreement", owner: "Maria Santos", dueDate: "2026-06-14", status: "open", priority: "high" },
    ],
    notes: [
      { id: "note-1", author: "Maria Santos", content: "Client prefers Credibly offer — lower factor rate. Scheduling call Thursday.", createdAt: "2026-06-10T14:30:00" },
    ],
    activities: [
      { id: "act-1", type: "offer", description: "Offer received from Credibly — $75,000 at 1.28 factor", user: "System", timestamp: "2026-06-10T09:15:00" },
      { id: "act-2", type: "application", description: "Application submitted to OnDeck", user: "Maria Santos", timestamp: "2026-06-04T11:00:00" },
      { id: "act-3", type: "stage", description: "Deal moved to Offers Received", user: "Maria Santos", timestamp: "2026-05-30T16:45:00" },
    ],
  },
  {
    id: "deal-2",
    businessName: "Sunrise Auto Repair",
    fundingAmount: 45000,
    owner: "Alex Rivera",
    stage: "submitted",
    daysInStage: 5,
    priority: "medium",
    lastActivity: "Submitted to Fora Financial",
    industry: "Automotive",
    annualRevenue: 380000,
    contactName: "Mike Chen",
    contactEmail: "mike@sunriseauto.com",
    contactPhone: "(786) 555-0198",
    source: "Google Search",
    applications: [
      { id: "app-5", lender: "Fora Financial", submissionDate: "2026-06-06", status: "under-review", assignedUser: "Alex Rivera" },
      { id: "app-6", lender: "Kabbage", submissionDate: "2026-06-07", status: "submitted", assignedUser: "Alex Rivera" },
    ],
    offers: [],
    documents: [
      { id: "doc-5", name: "Bank Statements (3 mo)", type: "Bank Statements", status: "verified", uploadedAt: "2026-06-01" },
      { id: "doc-6", name: "Driver License", type: "ID", status: "verified", uploadedAt: "2026-06-01" },
      { id: "doc-7", name: "Voided Check", type: "Banking", status: "verified", uploadedAt: "2026-06-02" },
    ],
    tasks: [
      { id: "task-3", title: "Follow up with Fora on status", owner: "Alex Rivera", dueDate: "2026-06-13", status: "open", priority: "medium" },
    ],
    notes: [],
    activities: [
      { id: "act-4", type: "application", description: "Application submitted to Kabbage", user: "Alex Rivera", timestamp: "2026-06-07T10:20:00" },
    ],
  },
  {
    id: "deal-3",
    businessName: "Green Leaf Landscaping",
    fundingAmount: 35000,
    owner: "Jordan Kim",
    stage: "collecting-docs",
    daysInStage: 3,
    priority: "medium",
    lastActivity: "Requested bank statements",
    industry: "Landscaping",
    annualRevenue: 290000,
    contactName: "Carlos Diaz",
    contactEmail: "carlos@greenleaf.com",
    contactPhone: "(954) 555-0167",
    source: "Referral",
    applications: [],
    offers: [],
    documents: [
      { id: "doc-8", name: "Bank Statements (3 mo)", type: "Bank Statements", status: "requested", uploadedAt: null },
      { id: "doc-9", name: "Driver License", type: "ID", status: "received", uploadedAt: "2026-06-08" },
      { id: "doc-10", name: "Voided Check", type: "Banking", status: "missing", uploadedAt: null },
    ],
    tasks: [
      { id: "task-4", title: "Request bank statements", owner: "Jordan Kim", dueDate: "2026-06-11", status: "in-progress", priority: "high" },
      { id: "task-5", title: "Follow up with client", owner: "Jordan Kim", dueDate: "2026-06-12", status: "open", priority: "medium" },
    ],
    notes: [
      { id: "note-2", author: "Jordan Kim", content: "Client traveling until Wednesday — will send statements then.", createdAt: "2026-06-09T08:00:00" },
    ],
    activities: [
      { id: "act-5", type: "document", description: "Bank statements requested from client", user: "Jordan Kim", timestamp: "2026-06-09T08:00:00" },
    ],
  },
  {
    id: "deal-4",
    businessName: "Metro Fitness Studio",
    fundingAmount: 120000,
    owner: "Maria Santos",
    stage: "negotiating",
    daysInStage: 7,
    priority: "high",
    lastActivity: "Client reviewing final terms",
    industry: "Fitness",
    annualRevenue: 890000,
    contactName: "Sarah Williams",
    contactEmail: "sarah@metrofitness.com",
    contactPhone: "(305) 555-0234",
    source: "Meta — English Broad",
    applications: [
      { id: "app-7", lender: "CAN Capital", submissionDate: "2026-05-15", status: "approved", assignedUser: "Maria Santos" },
      { id: "app-8", lender: "Credibly", submissionDate: "2026-05-18", status: "approved", assignedUser: "Maria Santos" },
    ],
    offers: [
      { id: "off-3", lender: "CAN Capital", amount: 115000, factorRate: 1.24, term: "18 months", paymentFrequency: "Daily", status: "presented", expirationDate: "2026-06-15", dailyPayment: 425 },
      { id: "off-4", lender: "Credibly", amount: 120000, factorRate: 1.26, term: "15 months", paymentFrequency: "Daily", status: "accepted", expirationDate: "2026-06-16", dailyPayment: 438 },
    ],
    documents: [
      { id: "doc-11", name: "Bank Statements (3 mo)", type: "Bank Statements", status: "verified", uploadedAt: "2026-05-10" },
      { id: "doc-12", name: "Funding Agreement", type: "Agreement", status: "received", uploadedAt: "2026-06-10" },
    ],
    tasks: [
      { id: "task-6", title: "Finalize funding agreement", owner: "Maria Santos", dueDate: "2026-06-13", status: "in-progress", priority: "high" },
    ],
    notes: [],
    activities: [
      { id: "act-6", type: "offer", description: "Client accepted Credibly offer — $120,000", user: "Maria Santos", timestamp: "2026-06-10T15:00:00" },
    ],
  },
  {
    id: "deal-5",
    businessName: "Coastal Dental Group",
    fundingAmount: 200000,
    owner: "Alex Rivera",
    stage: "ready-to-submit",
    daysInStage: 2,
    priority: "high",
    lastActivity: "All docs verified",
    industry: "Healthcare",
    annualRevenue: 1450000,
    contactName: "Dr. Emily Park",
    contactEmail: "emily@coastaldental.com",
    contactPhone: "(561) 555-0189",
    source: "Email Campaign",
    applications: [
      { id: "app-9", lender: "CAN Capital", submissionDate: null, status: "draft", assignedUser: "Alex Rivera" },
    ],
    offers: [],
    documents: [
      { id: "doc-13", name: "Bank Statements (6 mo)", type: "Bank Statements", status: "verified", uploadedAt: "2026-06-07" },
      { id: "doc-14", name: "Driver License", type: "ID", status: "verified", uploadedAt: "2026-06-07" },
      { id: "doc-15", name: "Voided Check", type: "Banking", status: "verified", uploadedAt: "2026-06-08" },
      { id: "doc-16", name: "Tax Returns", type: "Tax", status: "verified", uploadedAt: "2026-06-08" },
    ],
    tasks: [
      { id: "task-7", title: "Submit to CAN Capital and OnDeck", owner: "Alex Rivera", dueDate: "2026-06-11", status: "open", priority: "high" },
    ],
    notes: [],
    activities: [
      { id: "act-7", type: "document", description: "All required documents verified", user: "Alex Rivera", timestamp: "2026-06-09T17:00:00" },
    ],
  },
  {
    id: "deal-6",
    businessName: "Quick Print Solutions",
    fundingAmount: 25000,
    owner: "Jordan Kim",
    stage: "new",
    daysInStage: 1,
    priority: "low",
    lastActivity: "Deal created from lead",
    industry: "Printing",
    annualRevenue: 180000,
    contactName: "Tom Baker",
    contactEmail: "tom@quickprint.com",
    contactPhone: "(305) 555-0276",
    source: "Meta — Lead Form",
    applications: [],
    offers: [],
    documents: [],
    tasks: [
      { id: "task-8", title: "Initial qualification call", owner: "Jordan Kim", dueDate: "2026-06-12", status: "open", priority: "medium" },
    ],
    notes: [],
    activities: [
      { id: "act-8", type: "deal", description: "Deal created from marketing lead", user: "System", timestamp: "2026-06-10T08:30:00" },
    ],
  },
  {
    id: "deal-7",
    businessName: "Elite HVAC Services",
    fundingAmount: 65000,
    owner: "Maria Santos",
    stage: "qualified",
    daysInStage: 4,
    priority: "medium",
    lastActivity: "Qualification completed",
    industry: "Construction",
    annualRevenue: 520000,
    contactName: "Rick Johnson",
    contactEmail: "rick@elitehvac.com",
    contactPhone: "(954) 555-0312",
    source: "Google Search",
    applications: [],
    offers: [],
    documents: [
      { id: "doc-17", name: "Driver License", type: "ID", status: "received", uploadedAt: "2026-06-06" },
    ],
    tasks: [],
    notes: [],
    activities: [
      { id: "act-9", type: "stage", description: "Deal moved to Qualified", user: "Maria Santos", timestamp: "2026-06-06T14:00:00" },
    ],
  },
  {
    id: "deal-8",
    businessName: "Bella's Boutique",
    fundingAmount: 30000,
    owner: "Alex Rivera",
    stage: "funded",
    daysInStage: 21,
    priority: "low",
    lastActivity: "Commission collected",
    industry: "Retail",
    annualRevenue: 245000,
    contactName: "Isabella Cruz",
    contactEmail: "bella@bellasboutique.com",
    contactPhone: "(786) 555-0245",
    source: "Referral",
    applications: [
      { id: "app-10", lender: "Credibly", submissionDate: "2026-04-20", status: "approved", assignedUser: "Alex Rivera" },
    ],
    offers: [
      { id: "off-5", lender: "Credibly", amount: 28000, factorRate: 1.30, term: "10 months", paymentFrequency: "Daily", status: "accepted", expirationDate: "2026-05-01", dailyPayment: 145 },
    ],
    documents: [
      { id: "doc-18", name: "Funding Agreement", type: "Agreement", status: "verified", uploadedAt: "2026-05-01" },
    ],
    tasks: [],
    notes: [],
    activities: [
      { id: "act-10", type: "funded", description: "Deal funded — $28,000 via Credibly", user: "System", timestamp: "2026-05-05T10:00:00" },
    ],
  },
  {
    id: "deal-9",
    businessName: "Pacific Plumbing Co",
    fundingAmount: 55000,
    owner: "Jordan Kim",
    stage: "lost",
    daysInStage: 30,
    priority: "low",
    lastActivity: "Client went with competitor",
    industry: "Plumbing",
    annualRevenue: 410000,
    contactName: "Dan Wilson",
    contactEmail: "dan@pacificplumbing.com",
    contactPhone: "(305) 555-0398",
    source: "Meta — Lead Form",
    applications: [
      { id: "app-11", lender: "Rapid Finance", submissionDate: "2026-04-10", status: "declined", assignedUser: "Jordan Kim" },
    ],
    offers: [],
    documents: [],
    tasks: [],
    notes: [
      { id: "note-3", author: "Jordan Kim", content: "Client accepted offer from competitor at lower factor rate.", createdAt: "2026-05-11T11:00:00" },
    ],
    activities: [
      { id: "act-11", type: "stage", description: "Deal moved to Lost", user: "Jordan Kim", timestamp: "2026-05-11T11:00:00" },
    ],
  },
];

export const lenders: Lender[] = [
  {
    id: "lender-1",
    name: "CAN Capital",
    website: "https://www.cancapital.com",
    contactName: "James Porter",
    contactEmail: "jporter@cancapital.com",
    contactPhone: "(800) 555-0101",
    fundingTypes: ["MCA", "Term Loan"],
    minAmount: 10000,
    maxAmount: 250000,
    industries: ["Restaurant", "Retail", "Healthcare", "Construction"],
    notes: "Strong for restaurant deals $50K+. Fast turnaround on approvals.",
    applicationsSubmitted: 142,
    approvalRate: 68,
    fundingRate: 52,
    averageDealSize: 72000,
    averageResponseDays: 2,
    averageOfferAmount: 76000,
  },
  {
    id: "lender-2",
    name: "Credibly",
    website: "https://www.credibly.com",
    contactName: "Lisa Chen",
    contactEmail: "lchen@credibly.com",
    contactPhone: "(800) 555-0102",
    fundingTypes: ["MCA", "Line of Credit"],
    minAmount: 5000,
    maxAmount: 400000,
    industries: ["Restaurant", "Fitness", "Automotive", "Services"],
    notes: "Competitive factor rates. Good for deals under $100K.",
    applicationsSubmitted: 198,
    approvalRate: 72,
    fundingRate: 58,
    averageDealSize: 58000,
    averageResponseDays: 1,
    averageOfferAmount: 62000,
  },
  {
    id: "lender-3",
    name: "Rapid Finance",
    website: "https://www.rapidfinance.com",
    contactName: "Mark Stevens",
    contactEmail: "mstevens@rapidfinance.com",
    contactPhone: "(800) 555-0103",
    fundingTypes: ["MCA", "SBA"],
    minAmount: 25000,
    maxAmount: 500000,
    industries: ["Healthcare", "Construction", "Manufacturing"],
    notes: "Higher minimums. Best for established businesses with strong revenue.",
    applicationsSubmitted: 87,
    approvalRate: 55,
    fundingRate: 41,
    averageDealSize: 95000,
    averageResponseDays: 4,
    averageOfferAmount: 88000,
  },
  {
    id: "lender-4",
    name: "OnDeck",
    website: "https://www.ondeck.com",
    contactName: "Amy Rodriguez",
    contactEmail: "arodriguez@ondeck.com",
    contactPhone: "(800) 555-0104",
    fundingTypes: ["Term Loan", "Line of Credit"],
    minAmount: 5000,
    maxAmount: 250000,
    industries: ["All Industries"],
    notes: "Flexible terms. Good backup option for declined primary submissions.",
    applicationsSubmitted: 76,
    approvalRate: 61,
    fundingRate: 45,
    averageDealSize: 48000,
    averageResponseDays: 3,
    averageOfferAmount: 45000,
  },
  {
    id: "lender-5",
    name: "Fora Financial",
    website: "https://www.forafinancial.com",
    contactName: "David Kim",
    contactEmail: "dkim@forafinancial.com",
    contactPhone: "(800) 555-0105",
    fundingTypes: ["MCA"],
    minAmount: 5000,
    maxAmount: 500000,
    industries: ["Automotive", "Restaurant", "Retail", "Services"],
    notes: "Solid mid-market lender. Responsive rep team.",
    applicationsSubmitted: 64,
    approvalRate: 64,
    fundingRate: 49,
    averageDealSize: 52000,
    averageResponseDays: 2,
    averageOfferAmount: 50000,
  },
  {
    id: "lender-6",
    name: "Kabbage",
    website: "https://www.kabbage.com",
    contactName: "Rachel Green",
    contactEmail: "rgreen@kabbage.com",
    contactPhone: "(800) 555-0106",
    fundingTypes: ["Line of Credit"],
    minAmount: 2000,
    maxAmount: 150000,
    industries: ["E-commerce", "Retail", "Services"],
    notes: "Good for smaller deals. Fast automated decisions.",
    applicationsSubmitted: 53,
    approvalRate: 58,
    fundingRate: 42,
    averageDealSize: 32000,
    averageResponseDays: 1,
    averageOfferAmount: 30000,
  },
];

export const aiLenderRecommendation =
  "Based on similar funded deals in Restaurant and Fitness, CAN Capital and Credibly have the highest probability of approval for this profile. Credibly shows 72% approval rate with avg 1-day response for deals $50K–$100K.";
